#!/usr/bin/env bash
#
# fix-env-example.sh
# Generate or update .env.example for a project.
# Scans source files for env var reads (process.env.*, os.getenv, etc.),
# and compiles them into a .env.example template.
#
# Usage: ./fix-env-example.sh [--dry-run]
#
# Exit codes: 0 = .env.example is present and accurate
#             1 = env var references found but .env.example missing/incomplete

set -euo pipefail

FIX_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIX_REPO_ROOT="$(cd "$FIX_DIR/../../.." && pwd)"
source "$FIX_DIR/lib/fix-common.sh"
SCRIPT_DIR="$FIX_DIR"
source "$SCRIPT_DIR/lib/common.sh"

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

fix_section "FIX: .env.example Generation"

ENV_EXAMPLE="$FIX_REPO_ROOT/.env.example"

# ── Detect env var references ───────────────────────────────────────────────
fix_sub "Scanning for environment variable references..."

# Patterns to search for (per language)
declare -A PATTERNS
PATTERNS[js]='process\.env\.([A-Z_][A-Z0-9_]*)'
PATTERNS[ts]='process\.env\.([A-Z_][A-Z0-9_]*)'
PATTERNS[py]='os\.getenv\(['"'"'"]\([A-Z_][A-Z0-9_]*\)['"'"'"]'
PATTERNS[go]='os\.Getenv\(['"'"'"]\([A-Z_][A-Z0-9_]*\)['"'"'"]'
PATTERNS[rb]='ENV\[['"'"'"]\([A-Z_][A-Z0-9_]*\)['"'"'"]'
PATTERNS[rs]='env::var\(['"'"'"]\([A-Z_][A-Z0-9_]*\)['"'"'"]'
PATTERNS[sh]='\$\{[A-Z_][A-Z0-9_]*\}'
PATTERNS[yaml]='\$\{[A-Z_][A-Z0-9_]*\}'

ENV_VARS=()
TOTAL_FILES=0
TOTAL_MATCHES=0

for ext in "${!PATTERNS[@]}"; do
  pattern="${PATTERNS[$ext]}"
  # Find files with the extension
  while IFS= read -r -d '' file; do
    rel="${file#"$FIX_REPO_ROOT"/}"
    # Skip node_modules, .git, .gitnexus
    case "$rel" in
      node_modules/*|.git/*|.gitnexus/*) continue ;;
    esac
    ((TOTAL_FILES++)) || true
    matches=$(grep -oP "$pattern" "$file" 2>/dev/null || true)
    while IFS= read -r match; do
      [[ -z "$match" ]] && continue
      # Extract the variable name
      var=$(echo "$match" | grep -oP '[A-Z_][A-Z0-9_]{2,}' | head -1)
      [[ -z "$var" ]] && continue
      # Skip common false positives
      case "$var" in
        PATH|HOME|USER|PWD|SHELL|TERM|LANG|LC_ALL|DISPLAY|EDITOR) continue ;;
      esac
      if ! printf '%s\n' "${ENV_VARS[@]}" | grep -qFx "$var"; then
        ENV_VARS+=("$var")
      fi
      ((TOTAL_MATCHES++)) || true
    done <<< "$matches"
  done < <(find "$FIX_REPO_ROOT" -name "*.$ext" -type f -print0 2>/dev/null || true)
done

# Sort the env vars
mapfile -t ENV_VARS < <(printf '%s\n' "${ENV_VARS[@]}" | sort -u)

if [[ ${#ENV_VARS[@]} -eq 0 ]]; then
  fix_skip "No environment variable references found — .env.example not needed"
  if [[ -f "$ENV_EXAMPLE" ]]; then
    fix_info ".env.example exists but no env vars detected in code — may be stale"
  fi
  exit 0
fi

fix_sub "Found ${#ENV_VARS[@]} unique env vars across $TOTAL_FILES files (${TOTAL_MATCHES} total references):"
for var in "${ENV_VARS[@]}"; do
  fix_info "  $var"
done

# ── Check existing .env.example ─────────────────────────────────────────────
if [[ -f "$ENV_EXAMPLE" ]]; then
  fix_sub "Existing .env.example found"

  MISSING=()
  for var in "${ENV_VARS[@]}"; do
    if ! grep -qP "^(#\s*)?$var=" "$ENV_EXAMPLE" 2>/dev/null; then
      MISSING+=("$var")
    fi
  done

  if [[ ${#MISSING[@]} -eq 0 ]]; then
    fix_ok "All env vars documented in .env.example"
    exit 0
  fi

  fix_warn "${#MISSING[@]} env vars missing from .env.example:"
  for var in "${MISSING[@]}"; do
    fix_info "  $var (missing)"
  done

  if $DRY_RUN; then
    fix_info "[dry-run] would append ${#MISSING[@]} missing vars to .env.example"
    exit 1
  fi

  # Append missing vars
  fix_snapshot "$ENV_EXAMPLE"
  {
    echo ""
    echo "# Auto-detected env vars (added by repo-health fix)"
    for var in "${MISSING[@]}"; do
      echo "# $var="
    done
  } >> "$ENV_EXAMPLE"
  fix_ok "Appended ${#MISSING[@]} missing vars to .env.example"
else
  fix_warn "No .env.example found, but ${#ENV_VARS[@]} env vars detected"

  if $DRY_RUN; then
    fix_info "[dry-run] would create .env.example with ${#ENV_VARS[@]} vars"
    exit 1
  fi

  # Generate .env.example
  cat > "$ENV_EXAMPLE" << 'HEADER'
# .env.example — Environment Variables
#
# Copy this file to .env and fill in the values:
#   cp .env.example .env
#
# Auto-generated by repo-health fix-env-example.sh

HEADER
  for var in "${ENV_VARS[@]}"; do
    echo "# $var=" >> "$ENV_EXAMPLE"
  done
  echo "" >> "$ENV_EXAMPLE"
  echo "# === End of auto-detected vars ===" >> "$ENV_EXAMPLE"

  fix_ok "Created .env.example with ${#ENV_VARS[@]} variables"
fi

# ── Verify ──────────────────────────────────────────────────────────────────
if [[ -f "$ENV_EXAMPLE" ]]; then
  # Check the env example is in .gitignore — if not, warn
  if [[ -f "$FIX_REPO_ROOT/.gitignore" ]]; then
    if ! grep -q '^\.env$' "$FIX_REPO_ROOT/.gitignore" 2>/dev/null; then
      fix_warn ".env is not in .gitignore — consider adding it to prevent committing secrets"
    fi
  fi
  fix_ok ".env.example is present at $ENV_EXAMPLE"
fi

exit 0
